#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the CodeAppsTable
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr8ac_codeappstable_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the CodeAppsTable
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr8ac_codeappstable_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cr8ac_codeappstable")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class cr8ac_CodeAppsTable : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public cr8ac_CodeAppsTable() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "cr8ac_codeappstable";
	
	public const string EntityLogicalCollectionName = "cr8ac_codeappstables";
	
	public const string EntitySetName = "cr8ac_codeappstables";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr8ac_codeappstableid")]
	public System.Nullable<System.Guid> cr8ac_CodeAppsTableId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("cr8ac_codeappstableid");
		}
		set
		{
			this.OnPropertyChanging("cr8ac_CodeAppsTableId");
			this.SetAttributeValue("cr8ac_codeappstableid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("cr8ac_CodeAppsTableId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr8ac_codeappstableid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.cr8ac_CodeAppsTableId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr8ac_name")]
	public string cr8ac_Name
	{
		get
		{
			return this.GetAttributeValue<string>("cr8ac_name");
		}
		set
		{
			this.OnPropertyChanging("cr8ac_Name");
			this.SetAttributeValue("cr8ac_name", value);
			this.OnPropertyChanged("cr8ac_Name");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the CodeAppsTable
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual cr8ac_codeappstable_statecode? statecode
	{
		get
		{
			return ((cr8ac_codeappstable_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the CodeAppsTable
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual cr8ac_codeappstable_statuscode? statuscode
	{
		get
		{
			return ((cr8ac_codeappstable_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
